# Подключение к PostgreSQL (запущенному через Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/simpleshop
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate автоматически создаёт таблицы в базе
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Порт сервера
server.port=8080
